### ISSUE TITLE
"Input pointer misalignment." errors

### ISSUE THREAD

**Issue by billylanchantin** [acalejos/exgboost#31]
If this is too specific for an issue, I'm happy to move this discussion to elixirforum.

I'm getting errors that appear to be originating from the underlying XGBoost code.

Raw:

```
** (ArgumentError) raise/1 and reraise/2 expect a module name, string or exception as the first argument, got: ~c"[17:31:10] /home/runner/.cache/exgboost/xgboost-08ce495b5de973033160e7c7b650abf59346a984/src/c_api/../data/array_interface.h:410: Check failed: ptr % alignment == 0 (1 vs. 0) : Input pointer misalignment.\nStack trace:\n  [bt] (0) /home/billy/dwell_pred/_build/dev/lib/exgboost/priv/lib/libxgboost.so(+0x177eb8) [0x7f3a5f770eb8]\n  [bt] (1) /home/billy/dwell_pred/_build/dev/lib/exgboost/priv/lib/libxgboost.so(xgboost::ArrayInterface<2, false>::Initialize(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, xgboost::Json, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, xgboost::Json> > > const&)+0x5c1) [0x7f3a5f7a4811]\n  [bt] (2) /home/billy/dwell_pred/_build/dev/lib/exgboost/priv/lib/libxgboost.so(XGDMatrixCreateFromDense+0x162) [0x7f3a5f782582]\n  [bt] (3) /home/billy/dwell_pred/_build/dev/lib/exgboost/priv/libexgboost.so(EXGDMatrixCreateFromDense+0x88) [0x7f3b4c01fa08]\n  [bt] (4) /home/billy/.asdf/installs/erlang/26.1.2/erts-14.1.1/bin/beam.smp(beam_jit_call_nif(process*, void const*, unsigned long*, unsigned long (*)(enif_environment_t*, int, unsigned long*), erl_module_nif*)+0x78) [0x55f4b4749e68]\n  [bt] (5) [0x7f3b502626cf]\n\n"
    (exgboost 0.3.2) lib/exgboost/internal.ex:131: EXGBoost.Internal.unwrap!/1
    (exgboost 0.3.2) lib/exgboost/dmatrix.ex:285: EXGBoost.DMatrix.from_tensor/2
    (exgboost 0.3.2) lib/exgboost.ex:214: EXGBoost.train/3
    iex:21: (file)
```

Message formatted:

```
[17:28:44] /home/runner/.cache/exgboost/xgboost-08ce495b5de973033160e7c7b650abf59346a984/src/c_api/../data/array_interface.h:410: Check failed: ptr % alignment == 0 (1 vs. 0) : Input pointer misalignment.
Stack trace:
  [bt] (0) /home/billy/dwell_pred/_build/dev/lib/exgboost/priv/lib/libxgboost.so(+0x177eb8) [0x7f3a5f770eb8]
  [bt] (1) /home/billy/dwell_pred/_build/dev/lib/exgboost/priv/lib/libxgboost.so(xgboost::ArrayInterface<2, false>::Initialize(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, xgboost::Json, std::less<void>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, xgboost::Json> > > const&)+0x5c1) [0x7f3a5f7a4811]
  [bt] (2) /home/billy/dwell_pred/_build/dev/lib/exgboost/priv/lib/libxgboost.so(XGDMatrixCreateFromDense+0x162) [0x7f3a5f782582]
  [bt] (3) /home/billy/dwell_pred/_build/dev/lib/exgboost/priv/libexgboost.so(EXGDMatrixCreateFromDense+0x88) [0x7f3b4c01fa08]
  [bt] (4) /home/billy/.asdf/installs/erlang/26.1.2/erts-14.1.1/bin/beam.smp(beam_jit_call_nif(process*, void const*, unsigned long*, unsigned long (*)(enif_environment_t*, int, unsigned long*), erl_module_nif*)+0x78) [0x55f4b4749e68]
  [bt] (5) [0x7f3b502626cf]
```

I'm not sure what to make of it. This is roughly the code I'm calling:

```elixir
train_opts = [
  alpha: 2.0,
  disable_default_eval_metric: true,
  early_stopping_rounds: 8,
  eta: 0.0625,
  eval_metric: [:rmse],
  evals: [{x_test, y_test, "test"}],
  lambda: 2.0,
  max_depth: 8,
  num_boost_rounds: 2_048,
  objective: :reg_quantileerror,
  tree_method: :hist,
  verbose_eval: true
]

model_p05 = EXGBoost.train(x_train, y_train, Keyword.merge(train_opts, quantile_alpha: 0.05))
```

`x_train`, `y_train`, `x_test`, and `y_test` all have compatible shapes. There was a thing I had to do where they were initially created with the EXLA backend, but I had to switch backends to deal with https://github.com/acalejos/exgboost/issues/22. My process was to `Nx.serialize` each tensor then `Nx.deserialize` them back under the new backend. I also called `Nx.backend_transfer` for good measure, though I admit I don't understand the particulars there.

Any guidance would be appreciated! I can provide additional specs if they're needed to debug.

**Comment by acalejos** [comment]
Ok, try that and let me know what happens. You might also want to take a look at this thread and particularly this comment: https://github.com/acalejos/exgboost/issues/23#issuecomment-1722663846 as it relates to stack sizes in the BEAM and interactions with the NIF. Although your issue is different in that it is not crashing the BEAM

**Comment by acalejos** [comment]
Hmm if you're willing to share the rest of the code I can look into it more. Otherwise it's hard for me to dig much further into it. Might leave this open in case others find similar issues though

**Comment by billylanchantin** [comment]
We're not sure what happened here. I wasn't able to reliably reproduce. It was _probably_ some combination of EXGBoost versions, binary backends, and serializing/deserializing.

But I've got a working model now, so I think we can close this.
